name: Update Issue Board

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies (if any)
      - name: Install dependencies
        run: npm install
        # if you don't have a package.json you can skip this step

      # 4. Run your script
      - name: Generate board.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node list-projects-for-repo.mjs

      # 5. (Optional) Commit & push board.json back to the repo
      - name: Commit board.json
        if: github.event_name == 'push' || github.event_name == 'issues'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add board/_board.json
          git diff --quiet || git commit -m "chore(board): update board.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}